[package]
name = "aoc-2020"
version = "0.1.0"
authors = ["Christopher Daniel <cdaniel@ztech.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
